server:
  port: 8098
  
spring:
  application:
    name: ZullApiGateWay
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
